baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'My New Hugo Site'
publishDir = "public"



defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
  [languages.bn]
    languageName = "বাংলা"
    weight = 2
    contentDir = "content/bn"
